name: Publish SLCommandScript.Core NuGet package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: windows-latest
    steps:
    - name: Download Package
      id: download
      uses: robinraju/release-downloader@v1
      with:
        fileName: '*.nupkg'
        tag: ${{ github.event.release.tag_name }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Publish Package
      shell: pwsh
      run: |
        echo "Pushing file: ${{ fromJson(steps.download.outputs.downloaded_files)[0] }}"
        dotnet nuget push ${{ fromJson(steps.download.outputs.downloaded_files)[0] }} --api-key ${{ secrets.GITHUB_TOKEN }} --source github --skip-duplicate
        dotnet nuget push ${{ fromJson(steps.download.outputs.downloaded_files)[0] }} --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json --skip-duplicate
